// Generated by cdk-import
import * as cdk from "@aws-cdk/core"

/* eslint-disable @typescript-eslint/naming-convention */

/**
 * Datadog Monitors Downtime 3.1.0
 *
 * @schema CfnDowntimeProps
 */
export interface CfnDowntimeProps {
  /**
   * Whether or not this downtime is disabled
   *
   * @schema CfnDowntimeProps#Disabled
   */
  readonly disabled?: boolean

  /**
   * POSIX timestamp to end the downtime. If not provided, the downtime is in effect indefinitely (i.e. until you cancel it).
   *
   * @schema CfnDowntimeProps#End
   */
  readonly end?: number

  /**
   * Message on the downtime
   *
   * @schema CfnDowntimeProps#Message
   */
  readonly message?: string

  /**
   * A single monitor to which the downtime applies. If not provided, the downtime applies to all monitors.
   *
   * @schema CfnDowntimeProps#MonitorId
   */
  readonly monitorId?: number

  /**
   * A comma-separated list of monitor tags, to which the downtime applies. The resulting downtime applies to monitors that match ALL provided monitor tags.
   *
   * @schema CfnDowntimeProps#MonitorTags
   */
  readonly monitorTags?: string[]

  /**
   * The scope(s) to which the downtime applies
   *
   * @schema CfnDowntimeProps#Scope
   */
  readonly scope: string[]

  /**
   * POSIX timestamp to start the downtime. If not provided, the downtime starts the moment it is created.
   *
   * @schema CfnDowntimeProps#Start
   */
  readonly start?: number

  /**
   * The timezone for the downtime
   *
   * @schema CfnDowntimeProps#Timezone
   */
  readonly timezone?: string
}

/**
 * Converts an object of type 'CfnDowntimeProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_CfnDowntimeProps(
  obj: CfnDowntimeProps | undefined
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined
  }
  const result = {
    Disabled: obj.disabled,
    End: obj.end,
    Message: obj.message,
    MonitorId: obj.monitorId,
    MonitorTags: obj.monitorTags?.map(y => y),
    Scope: obj.scope?.map(y => y),
    Start: obj.start,
    Timezone: obj.timezone,
  }
  // filter undefined values
  return Object.entries(result).reduce(
    (r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }),
    {}
  )
}
/* eslint-enable max-len, quote-props */

/**
 * A CloudFormation `Datadog::Monitors::Downtime`
 *
 * @cloudformationResource Datadog::Monitors::Downtime
 * @stability external
 * @link arn:aws:cloudformation:us-west-2::type/resource/7171b96e5d207b947eb72ca9ce05247c246de623/Datadog-Monitors-Downtime
 */
export class CfnDowntime extends cdk.CfnResource {
  /**
   * The CloudFormation resource type name for this resource class.
   */
  public static readonly CFN_RESOURCE_TYPE_NAME = "Datadog::Monitors::Downtime"

  /**
   * Resource props.
   */
  public readonly props: CfnDowntimeProps

  /**
   * Attribute `Datadog::Monitors::Downtime.Active`
   * @link arn:aws:cloudformation:us-west-2::type/resource/7171b96e5d207b947eb72ca9ce05247c246de623/Datadog-Monitors-Downtime
   */
  public readonly attrActive: cdk.IResolvable
  /**
   * Attribute `Datadog::Monitors::Downtime.Canceled`
   * @link arn:aws:cloudformation:us-west-2::type/resource/7171b96e5d207b947eb72ca9ce05247c246de623/Datadog-Monitors-Downtime
   */
  public readonly attrCanceled: number
  /**
   * Attribute `Datadog::Monitors::Downtime.CreatorId`
   * @link arn:aws:cloudformation:us-west-2::type/resource/7171b96e5d207b947eb72ca9ce05247c246de623/Datadog-Monitors-Downtime
   */
  public readonly attrCreatorId: number
  /**
   * Attribute `Datadog::Monitors::Downtime.DowntimeType`
   * @link arn:aws:cloudformation:us-west-2::type/resource/7171b96e5d207b947eb72ca9ce05247c246de623/Datadog-Monitors-Downtime
   */
  public readonly attrDowntimeType: number
  /**
   * Attribute `Datadog::Monitors::Downtime.Id`
   * @link arn:aws:cloudformation:us-west-2::type/resource/7171b96e5d207b947eb72ca9ce05247c246de623/Datadog-Monitors-Downtime
   */
  public readonly attrId: number
  /**
   * Attribute `Datadog::Monitors::Downtime.ParentId`
   * @link arn:aws:cloudformation:us-west-2::type/resource/7171b96e5d207b947eb72ca9ce05247c246de623/Datadog-Monitors-Downtime
   */
  public readonly attrParentId: number
  /**
   * Attribute `Datadog::Monitors::Downtime.UpdaterId`
   * @link arn:aws:cloudformation:us-west-2::type/resource/7171b96e5d207b947eb72ca9ce05247c246de623/Datadog-Monitors-Downtime
   */
  public readonly attrUpdaterId: number

  /**
   * Create a new `Datadog::Monitors::Downtime`.
   *
   * @param scope - scope in which this resource is defined
   * @param id    - scoped id of the resource
   * @param props - resource properties
   */
  constructor(scope: cdk.Construct, id: string, props: CfnDowntimeProps) {
    super(scope, id, {
      type: CfnDowntime.CFN_RESOURCE_TYPE_NAME,
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion -- null return as parameter is not null
      properties: toJson_CfnDowntimeProps(props)!,
    })

    this.props = props

    this.attrActive = this.getAtt("Active")
    this.attrCanceled = cdk.Token.asNumber(this.getAtt("Canceled"))
    this.attrCreatorId = cdk.Token.asNumber(this.getAtt("CreatorId"))
    this.attrDowntimeType = cdk.Token.asNumber(this.getAtt("DowntimeType"))
    this.attrId = cdk.Token.asNumber(this.getAtt("Id"))
    this.attrParentId = cdk.Token.asNumber(this.getAtt("ParentId"))
    this.attrUpdaterId = cdk.Token.asNumber(this.getAtt("UpdaterId"))
  }
}
